-- Reconstructed Schema Dump for Project: cemgjbwgfauicsgabwdo
-- Generated by AI Assistant via introspection

--
-- Table: habits
--
CREATE TABLE public.habits (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    title text NOT NULL,
    description text,
    color text DEFAULT '#4ade80'::text,
    icon text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT habits_pkey PRIMARY KEY (id),
    CONSTRAINT habits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

--
-- Table: habit_logs
--
CREATE TABLE public.habit_logs (
    id uuid NOT NULL,
    habit_id uuid NOT NULL,
    completed_at text NOT NULL,
    status text DEFAULT 'completed'::text,
    CONSTRAINT habit_logs_pkey PRIMARY KEY (id),
    CONSTRAINT habit_logs_habit_id_fkey FOREIGN KEY (habit_id) REFERENCES public.habits(id)
);

CREATE UNIQUE INDEX habit_logs_habit_id_completed_at_key ON public.habit_logs USING btree (habit_id, completed_at);

--
-- Table: habit_notes
--
CREATE TABLE public.habit_notes (
    id uuid NOT NULL,
    habit_id uuid NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT habit_notes_pkey PRIMARY KEY (id),
    CONSTRAINT habit_notes_habit_id_fkey FOREIGN KEY (habit_id) REFERENCES public.habits(id)
);

--
-- Table: projects
--
CREATE TABLE public.projects (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    color text DEFAULT '#3b82f6'::text,
    icon text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

--
-- Table: project_features
--
CREATE TABLE public.project_features (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    title text NOT NULL,
    description text,
    priority text DEFAULT 'medium'::text,
    status text DEFAULT 'pending'::text,
    completed boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT project_features_pkey PRIMARY KEY (id),
    CONSTRAINT project_features_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);

--
-- Row Level Security
--
ALTER TABLE public.habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.habit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.habit_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_features ENABLE ROW LEVEL SECURITY;

--
-- Policies
--

-- Table: habits
CREATE POLICY "Habits: Users can CRUD own" ON public.habits
    FOR ALL
    TO public
    USING (auth.uid() = user_id);

-- Table: habit_logs
CREATE POLICY "Logs: Users can CRUD own" ON public.habit_logs
    FOR ALL
    TO public
    USING (EXISTS ( SELECT 1
   FROM habits
  WHERE ((habits.id = habit_logs.habit_id) AND (habits.user_id = auth.uid()))));

-- Table: habit_notes
CREATE POLICY "Notes: Users can CRUD own" ON public.habit_notes
    FOR ALL
    TO public
    USING (EXISTS ( SELECT 1
   FROM habits
  WHERE ((habits.id = habit_notes.habit_id) AND (habits.user_id = auth.uid()))));

-- Table: projects
CREATE POLICY "Projects: Users can CRUD own" ON public.projects
    FOR ALL
    TO public
    USING (auth.uid() = user_id);

-- Table: project_features
CREATE POLICY "Features: Users can CRUD own" ON public.project_features
    FOR ALL
    TO public
    USING (EXISTS ( SELECT 1
   FROM projects
  WHERE ((projects.id = project_features.project_id) AND (projects.user_id = auth.uid()))));
