import { Copy, Send, Lightbulb } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import {
	type Project,
	type ProjectFeature,
	ProjectService,
} from "../../backbone/services/projectService";
import { useToast } from "../../context/ToastContext";
import { VoiceInput } from "../ui/VoiceInput";
import { Drawer } from "../design/Drawer";
import { NeonButton } from "../design/NeonButton";
import { ConfirmationModal } from "../ui/ConfirmationModal";
import { SwipeableItem } from "../design/SwipeableItem";

interface ProjectDetailModalProps {
	project: Project;
	onClose: () => void;
	onUpdate?: () => void;
}

export function ProjectDetailModal({
	project,
	onClose,
	onUpdate,
}: ProjectDetailModalProps) {
	const [features, setFeatures] = useState<ProjectFeature[]>([]);
	const { success, error } = useToast();
	const [newFeature, setNewFeature] = useState("");
	const [loading, setLoading] = useState(false);
	const [loadingData, setLoadingData] = useState(true);
	const listEndRef = useRef<HTMLDivElement>(null);

	// Swipe & Confirm State
	const [featureToDelete, setFeatureToDelete] = useState<ProjectFeature | null>(null);
	const [resetKeys, setResetKeys] = useState<Record<string, number>>({});

	const loadFeatures = useCallback(async () => {
		try {
			setLoadingData(true);
			const data = await ProjectService.fetchFeatures(project.id);
			setFeatures(data);
		} catch (err) {
			console.error(err);
		} finally {
			setLoadingData(false);
		}
	}, [project.id]);

	useEffect(() => {
		loadFeatures();
	}, [loadFeatures]);

	useEffect(() => {
		if (features.length > 0) {
			listEndRef.current?.scrollIntoView({ behavior: "smooth" });
		}
	}, [features.length]);

	const handleAddFeature = async () => {
		if (!newFeature.trim()) return;
		setLoading(true);
		try {
			const feature = await ProjectService.addFeature({
				project_id: project.id,
				title: newFeature,
			});
			setFeatures([...features, feature]);
			setNewFeature("");
			onUpdate?.();
		} catch (err) {
			console.error(err);
			error("Failed to add feature");
		} finally {
			setLoading(false);
		}
	};

	const handleSwipeDelete = (feature: ProjectFeature) => {
		setFeatureToDelete(feature);
	};

	const confirmDelete = async () => {
		if (!featureToDelete) return;

		try {
			await ProjectService.deleteFeature(featureToDelete.id);
			setFeatures(features.filter((f) => f.id !== featureToDelete.id));
			onUpdate?.();
			success("Deleted");
		} catch (err) {
			console.error(err);
			error("Failed to delete");
		} finally {
			setFeatureToDelete(null);
		}
	};

	const cancelDelete = () => {
		if (featureToDelete) {
			setResetKeys(prev => ({
				...prev,
				[featureToDelete.id]: (prev[featureToDelete.id] || 0) + 1
			}));
		}
		setFeatureToDelete(null);
	};

	const handleExport = () => {
		const markdown = `# Project: ${project.name}\n\n${project.description || ""}\n\n## Features\n${features.map((f, i) => `${i + 1}. **${f.title}**\n   ${f.description || ""}`).join("\n\n")}\n\n---\n* Generated by OSSFlow * `;
		navigator.clipboard.writeText(markdown);
		success("Markdown copied to clipboard!");
	};

	return (
		<Drawer
			isOpen={true}
			onClose={onClose}
			title={project.name}
			noScroll
		>
			<div className="flex-1 overflow-y-auto px-6 pt-4 pb-0 no-scrollbar">
				{/* Sub-header info */}
				<div className="mb-6 text-[var(--text-secondary)] flex items-center justify-between">
					<span>{features.length} features planned</span>
					<button
						onClick={handleExport}
						className="p-2 bg-white/5 rounded-full hover:bg-white/10 text-white transition-colors"
					>
						<Copy size={16} />
					</button>
				</div>

				{/* List */}
				<div className="flex flex-col gap-3 min-h-[100px] mb-6">
					{loadingData ? (
						<div className="flex justify-center py-10">
							<div className="animate-spin w-8 h-8 border-2 border-[var(--color-primary)] border-t-transparent rounded-full" />
						</div>
					) : (
						<>
							{features.map((feature, i) => {
								const currentKey = `${feature.id}-${resetKeys[feature.id] || 0}`;
								return (
									<SwipeableItem
										key={currentKey}
										onDelete={() => handleSwipeDelete(feature)}
										confirmMessage="Delete feature?"
									>
										<div
											className="group relative bg-[var(--bg-deep)] border border-white/5 rounded-xl p-4 flex gap-3 animated-fade-in"
										>
											<span className="font-mono text-[var(--color-primary)] font-bold pt-1">{i + 1}.</span>
											<div className="flex-1">
												<h4 className="font-medium text-[var(--text-primary)] leading-tight">{feature.title}</h4>
												{feature.description && (
													<p className="text-sm text-[var(--text-secondary)] mt-1">{feature.description}</p>
												)}
											</div>
											{/* No Trash Icon */}
										</div>
									</SwipeableItem>
								);
							})}

							{features.length === 0 && (
								<div className="text-center py-10 text-[var(--text-tertiary)] bg-white/5 rounded-xl border border-dashed border-white/10">
									<Lightbulb className="mx-auto mb-2 opacity-50" />
									<p>Capture your first feature idea below.</p>
								</div>
							)}
						</>
					)}
					<div ref={listEndRef} />
				</div>
			</div>

			{/* Input Area - Fixed at Bottom */}
			<div className="flex-none bg-[var(--bg-surface)] p-4 border-t border-white/10 flex items-end gap-2 z-10 pb-6">
				<VoiceInput
					value={newFeature}
					onValueChange={setNewFeature}
					placeholder="Add a feature..."
					className="flex-1 bg-[var(--bg-deep)] border-white/10 rounded-xl px-4 py-3 focus:border-[var(--color-primary)] outline-none transition-colors no-scrollbar"
				/>
				<NeonButton
					onClick={handleAddFeature}
					disabled={!newFeature.trim() || loading}
					className="!w-12 !h-12 !p-0 !rounded-xl flex-shrink-0"
					glow
				>
					{loading ? <div className="w-4 h-4 border-2 border-black border-t-transparent rounded-full animate-spin" /> : <Send size={20} />}
				</NeonButton>
			</div>

			{featureToDelete && (
				<ConfirmationModal
					isOpen={!!featureToDelete}
					onClose={cancelDelete}
					onConfirm={confirmDelete}
					title="Delete Feature?"
					message={`Delete "${featureToDelete.title}"?`}
				/>
			)}
		</Drawer>
	);
}
