import {
	Button,
	makeStyles,
	tokens,
	shorthands,
	Text,
	Spinner,
	Dialog,
	DialogSurface,
	DialogBody
} from "@fluentui/react-components";
import {
	Dismiss24Regular,
	Copy24Regular,
	Delete24Regular,
	Send24Regular
} from "@fluentui/react-icons";
import { useCallback, useEffect, useRef, useState } from "react";
import {
	type Project,
	type ProjectFeature,
	ProjectService,
} from "../../backbone/services/projectService";
import { useToast } from "../../context/ToastContext";
import { VoiceInput } from "../ui/VoiceInput";

const useStyles = makeStyles({
	dialogSurface: {
		width: "100%",
		maxWidth: "100%",
		position: "fixed",
		bottom: 0,
		left: 0,
		right: 0,
		margin: 0,
		height: "85dvh", // Taller for details
		maxHeight: "90dvh",
		...shorthands.borderRadius(tokens.borderRadiusXLarge, tokens.borderRadiusXLarge, 0, 0),
		display: "flex",
		flexDirection: "column",

		"@media (min-width: 768px)": {
			width: "600px",
			maxWidth: "600px",
			position: "relative",
			bottom: "auto",
			left: "auto",
			right: "auto",
			margin: "auto",
			height: "auto",
			maxHeight: "80vh",
			...shorthands.borderRadius(tokens.borderRadiusLarge),
		}
	},
	header: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
		paddingBottom: "16px",
		borderBottom: `1px solid ${tokens.colorNeutralStroke2}`
	},
	contentNode: {
		display: "flex",
		flexDirection: "column",
		flexGrow: 1,
		overflowY: "auto",
		paddingTop: "16px",
		paddingBottom: "16px",
		...shorthands.gap("12px")
	},
	featureItem: {
		display: "flex",
		alignItems: "flex-start",
		...shorthands.gap("12px"),
		...shorthands.padding("12px"),
		backgroundColor: tokens.colorNeutralBackground2,
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		boxShadow: tokens.shadow2
	},
	featureContent: {
		flexGrow: 1,
		display: "flex",
		flexDirection: "column",
	},
	inputArea: {
		marginTop: "auto",
		paddingTop: "16px",
		borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
		display: "flex",
		alignItems: "flex-end",
		...shorthands.gap("8px")
	}
});

interface ProjectDetailModalProps {
	project: Project;
	onClose: () => void;
	onUpdate?: () => void;
}

export function ProjectDetailModal({
	project,
	onClose,
	onUpdate,
}: ProjectDetailModalProps) {
	const styles = useStyles();
	const [features, setFeatures] = useState<ProjectFeature[]>([]);
	const { success, error } = useToast();
	const [newFeature, setNewFeature] = useState("");
	const [_loading, setLoading] = useState(false);
	const [loadingData, setLoadingData] = useState(true);
	const listEndRef = useRef<HTMLDivElement>(null);

	const loadFeatures = useCallback(async () => {
		try {
			setLoadingData(true);
			const data = await ProjectService.fetchFeatures(project.id);
			setFeatures(data);
		} catch (err) {
			console.error(err);
		} finally {
			setLoadingData(false);
		}
	}, [project.id]);

	useEffect(() => {
		loadFeatures();
	}, [loadFeatures]);

	useEffect(() => {
		if (features.length > 0) {
			listEndRef.current?.scrollIntoView({ behavior: "smooth" });
		}
	}, [features.length]);

	const handleAddFeature = async () => {
		if (!newFeature.trim()) return;
		setLoading(true);
		try {
			const feature = await ProjectService.addFeature({
				project_id: project.id,
				title: newFeature,
			});
			setFeatures([...features, feature]);
			setNewFeature("");
			onUpdate?.();
		} catch (err) {
			console.error(err);
			error("Failed to add feature");
		} finally {
			setLoading(false);
		}
	};

	const handleDeleteFeature = async (id: string) => {
		try {
			await ProjectService.deleteFeature(id);
			setFeatures(features.filter((f) => f.id !== id));
			onUpdate?.();
		} catch (err) {
			console.error(err);
		}
	};

	const handleExport = () => {
		// ... (Keep existing export logic)
		const markdown = `# Project: ${project.name}\n\n${project.description || ""}\n\n## Features\n${features.map((f, i) => `${i + 1}. **${f.title}**\n   ${f.description || ""}`).join("\n\n")}\n\n---\n* Generated by OSSFlow * `;
		navigator.clipboard.writeText(markdown);
		success("Markdown copied to clipboard!");
	};

	return (
		<Dialog open={true} onOpenChange={(_, data) => !data.open && onClose()}>
			<DialogSurface className={styles.dialogSurface}>
				<DialogBody style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
					<div className={styles.header}>
						<div style={{ overflow: 'hidden' }}>
							<Text truncate weight="bold" size={500} block>{project.name}</Text>
							<Text size={200} style={{ color: tokens.colorNeutralForeground3 }}>{features.length} features planned</Text>
						</div>
						<div style={{ display: 'flex', gap: '8px' }}>
							<Button appearance="subtle" icon={<Copy24Regular />} onClick={handleExport} title="Copy Markdown" />
							<Button appearance="subtle" icon={<Dismiss24Regular />} onClick={onClose} title="Close" />
						</div>
					</div>

					<div className={styles.contentNode}>
						{loadingData && <Spinner label="Loading features..." />}
						{!loadingData && features.map((feature, i) => (
							<div key={feature.id} className={styles.featureItem}>
								<Text style={{ color: tokens.colorBrandForeground1, fontWeight: 'bold' }}>{i + 1}.</Text>
								<div className={styles.featureContent}>
									<Text weight="medium">{feature.title}</Text>
									{feature.description && <Text size={200} style={{ color: tokens.colorNeutralForeground3 }}>{feature.description}</Text>}
								</div>
								<Button
									appearance="transparent"
									icon={<Delete24Regular />}
									onClick={() => handleDeleteFeature(feature.id)}
									style={{ color: tokens.colorPaletteRedForeground1 }}
								/>
							</div>
						))}
						{!loadingData && features.length === 0 && (
							<Text align="center" style={{ padding: '40px', color: tokens.colorNeutralForeground3 }}>No features yet.</Text>
						)}
						<div ref={listEndRef} />
					</div>

					<div className={styles.inputArea}>
						<VoiceInput
							value={newFeature}
							onValueChange={setNewFeature}
							placeholder="Add a feature..."
							className="flex-grow"
							containerClassName="flex-grow"
						/>
						<Button
							appearance="primary"
							icon={<Send24Regular />}
							disabled={!newFeature.trim()}
							onClick={handleAddFeature}
						/>
					</div>
				</DialogBody>
			</DialogSurface>
		</Dialog>
	);
}
