
import { AnimatePresence, motion } from "framer-motion";
import { Copy, Send, X, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState, useRef } from "react";
import { useToast } from "../../context/ToastContext";
import {
	type Project,
	type ProjectFeature,
	ProjectService,
} from "../../backbone/services/projectService";
import { LoadingOverlay } from "../ui/LoadingOverlay";
import { VoiceInput } from "../ui/VoiceInput";

interface ProjectDetailModalProps {
	project: Project;
	onClose: () => void;
	onUpdate?: () => void;
}

export function ProjectDetailModal({
	project,
	onClose,
	onUpdate,
}: ProjectDetailModalProps) {
	const [features, setFeatures] = useState<ProjectFeature[]>([]);
	const { success, error } = useToast();
	const [newFeature, setNewFeature] = useState("");
	const [_loading, setLoading] = useState(false);
	const [loadingData, setLoadingData] = useState(true);
	const listEndRef = useRef<HTMLDivElement>(null);

	const loadFeatures = useCallback(async () => {
		try {
			setLoadingData(true);
			const data = await ProjectService.fetchFeatures(project.id);
			setFeatures(data);
		} catch (err) {
			console.error(err);
		} finally {
			setLoadingData(false);
		}
	}, [project.id]);

	useEffect(() => {
		loadFeatures();
	}, [loadFeatures]);

	// Auto-scroll to bottom when features change
	useEffect(() => {
		if (features.length > 0) {
			listEndRef.current?.scrollIntoView({ behavior: "smooth" });
		}
	}, [features.length]);

	const handleAddFeature = async () => {
		if (!newFeature.trim()) return;
		setLoading(true);
		try {
			const feature = await ProjectService.addFeature({
				project_id: project.id,
				title: newFeature,
			});
			setFeatures([...features, feature]);
			setNewFeature("");
			onUpdate?.(); // Notify parent
		} catch (err) {
			console.error(err);
			error("Failed to add feature");
		} finally {
			setLoading(false);
		}
	};

	const handleDeleteFeature = async (id: string) => {
		try {
			await ProjectService.deleteFeature(id);
			setFeatures(features.filter((f) => f.id !== id));
			onUpdate?.(); // Notify parent
		} catch (err) {
			console.error(err);
		}
	};

	const handleExport = () => {
		const markdown = `# Project: ${project.name}

${project.description || ""}

## Features
${features
				.map(
					(f, i) => `${i + 1}. **${f.title}**
   ${f.description || ""}`,
				)
				.join("\n\n")
			}

---
* Generated by OSSFlow * `;

		navigator.clipboard.writeText(markdown);
		success("Markdown copied to clipboard!");
	};

	return (
		<div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
			<motion.div
				initial={{ opacity: 0, scale: 0.9 }}
				animate={{ opacity: 1, scale: 1 }}
				exit={{ opacity: 0, scale: 0.9 }}
				className="relative w-full max-w-md h-[80vh] flex flex-col"
			>
				{(_loading || loadingData) && (
					<LoadingOverlay
						message={loadingData ? "Loading features..." : "Updating..."}
					/>
				)}

				{/* Modal Card */}
				<div className="flex-1 flex flex-col glass-3d rounded-3xl overflow-hidden relative z-10 bg-zen-surface">
					<div className="glow-behind bg-cyan-500/20 pointer-events-none" />

					{/* Header */}
					<div className="p-6 border-b border-black/5 dark:border-white/5 backdrop-blur-md flex justify-between items-center gap-4 shrink-0">
						<div className="flex-1 min-w-0">
							<h2 className="text-xl font-bold text-zen-text truncate">
								{project.name}
							</h2>
							<p className="text-xs text-zen-text-muted truncate">
								{features.length} features planned
							</p>
						</div>
						<div className="flex items-center gap-2">
							<button
								onClick={handleExport}
								className="p-2 bg-black/5 dark:bg-white/5 rounded-full hover:bg-black/10 dark:hover:bg-white/10 text-zen-text-muted hover:text-cyan-500 transition-colors"
								title="Copy Markdown"
							>
								<Copy size={18} />
							</button>
							<button
								onClick={onClose}
								className="p-2 bg-black/5 dark:bg-white/5 rounded-full hover:bg-black/10 dark:hover:bg-white/10"
							>
								<X size={20} />
							</button>
						</div>
					</div>

					{/* Features List */}
					<div className="flex-1 overflow-y-auto p-4 space-y-3">
						<AnimatePresence>
							{features.map((feature, i) => (
								<motion.div
									key={feature.id}
									initial={{ opacity: 0, y: 10 }}
									animate={{ opacity: 1, y: 0 }}
									exit={{ opacity: 0, y: -10 }}
									className="group flex gap-3 p-4 bg-black/5 dark:bg-white/5 border border-black/5 dark:border-white/5 rounded-xl items-start"
								>
									<span className="text-cyan-500 font-mono font-bold mt-0.5 shrink-0">
										{i + 1}.
									</span>
									<div className="flex-1 min-w-0 break-words">
										<h4 className="font-medium text-zen-text leading-tight">
											{feature.title}
										</h4>
										{feature.description && (
											<p className="text-sm text-zen-text-muted mt-1">
												{feature.description}
											</p>
										)}
									</div>
									<button
										onClick={() => handleDeleteFeature(feature.id)}
										className="shrink-0 p-2 text-zen-text-muted hover:text-red-500 hover:bg-red-500/10 rounded-lg transition-colors"
										title="Delete"
									>
										<Trash2 size={18} />
									</button>
								</motion.div>
							))}
						</AnimatePresence>
						<div ref={listEndRef} />
						{features.length === 0 && (
							<div className="text-center text-zen-text-muted/50 py-10 text-sm">
								No features yet. What needs to be built?
							</div>
						)}
					</div>

					{/* Input Area */}
					<div className="p-4 bg-black/20 backdrop-blur-md border-t border-white/5 z-20 shrink-0">
						<VoiceInput
							value={newFeature}
							onValueChange={setNewFeature}
							placeholder="Add a feature..."
							rows={1}
							style={{ minHeight: "3rem" }}
							onKeyDown={(e) => {
								if (e.key === "Enter" && !e.shiftKey) {
									e.preventDefault();
									handleAddFeature();
								}
							}}
							rightElement={
								<button
									onClick={handleAddFeature}
									disabled={!newFeature.trim()}
									className="p-2 bg-cyan-600 text-white rounded-xl hover:opacity-90 active:scale-95 disabled:opacity-50 transition-all"
								>
									<Send size={16} />
								</button>
							}
						/>
					</div>
				</div>
			</motion.div>
		</div>
	);
}
